### ISSUE TITLE
Installing cask applications fails

### ISSUE THREAD

**Issue by anthonygreen** [geerlingguy/ansible-role-homebrew#10]
If I try and run just the 'Install configured cask applications' task without the 'et list of apps installed with cask.' task and remove the when clause, the remaining cask task still fails:

TASK: [geerlingguy.homebrew | Install configured cask applications.] ********** 
<localhost> ESTABLISH CONNECTION FOR USER: vagrant
<localhost> REMOTE_MODULE command brew cask install firefox --appdir=/Users/vagrant/Applications
<localhost> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/greena28/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 localhost /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434018141.95-212269048581360 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434018141.95-212269048581360 && echo $HOME/.ansible/tmp/ansible-tmp-1434018141.95-212269048581360'
<localhost> PUT /var/folders/sm/vgbwtrps3yv2yl79n43t_f916ldxgl/T/tmpYpLcVk TO /Users/vagrant/.ansible/tmp/ansible-tmp-1434018141.95-212269048581360/command
<localhost> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/greena28/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 localhost /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/vagrant/.ansible/tmp/ansible-tmp-1434018141.95-212269048581360/command; rm -rf /Users/vagrant/.ansible/tmp/ansible-tmp-1434018141.95-212269048581360/ >/dev/null 2>&1'
failed: [test] => (item=firefox) => {"cmd": "brew cask install firefox --appdir=/Users/vagrant/Applications", "failed": true, "item": "firefox", "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/greena28/io.retry

test                       : ok=6    changed=0    unreachable=0    failed=1

**Comment by anthonygreen** [comment]
Switched to using the ansible homebrew module

**Comment by geerlingguy** [comment]
See fix in #9 - This should be working a bit better now, since the `brew` command is now run with the full path.
