### ISSUE TITLE
Homebrew update not allowing sudo

### ISSUE THREAD

**Issue by mattheo-geoffray** [geerlingguy/ansible-role-homebrew#106]
Hello

Since the last update of Homebrew there is an error about Homebrew not allowing the usage of `sudo`
```
TASK [geerlingguy.homebrew : Where is the cache?] ******************************
fatal: [local]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/brew", "--cache"], "delta": "0:00:00.272510", "end": "2018-09-06 14:55:17.341289", "msg": "non-zero return code", "rc": 1, "start": "2018-09-06 14:55:17.068779", "stderr": "Error: Running Homebrew as root is extremely dangerous and no longer supported.\nAs Homebrew does not drop privileges on installation you would be giving all\nbuild scripts full access to your system.", "stderr_lines": ["Error: Running Homebrew as root is extremely dangerous and no longer supported.", "As Homebrew does not drop privileges on installation you would be giving all", "build scripts full access to your system."], "stdout": "", "stdout_lines": []}
```

**Homebrew version**: 1.7.3
**Role version**: 2.6.0

Do you have an idea on how to fix this?

Thank you!

Matthéo

**Comment by elliotweiser** [comment]
It sounds like you are using privilege escalation when you shouldn't be. 

Are you passing `-b` or `--become` on the command-line?
Are you setting `become: yes` or `become: true` on the play that executes the Homebrew role?

Can't do that with Homebrew.

**Comment by mattheo-geoffray** [comment]
@elliotweiser 
Oh yes you're right I was using `ansible_become: yes` in my inventory... My bad!  
Thank you for the tip and the quick answer!
