### ISSUE TITLE
Ensure /usr/local/share/man/man5 and /usr/local/share/info have correct permissions

### ISSUE THREAD

**Issue by Fregf** [geerlingguy/ansible-role-homebrew#123]
Clean MacOS installation, installing Homebrew Casks and Formula with this ansible role. Casks install fine, then it starts installing formula,  and any of them fails:

`failed: [host.example.org] (item=sbcl) => {"ansible_loop_var": "item", "changed": false, "item": "sbcl", "msg": "Error: The following directories are not writable by your user:\n/usr/local/share/info\n/usr/local/share/man/man5\n\nYou should change the ownership of these directories to your user.\n  sudo chown -R $(whoami) /usr/local/share/info /usr/local/share/man/man5\n\nAnd make sure that your user has write permission.\n  chmod u+w /usr/local/share/info /usr/local/share/man/man5"}`
`
/usr/local/share/man/man5 and /usr/local/share/info are  owned by root, and not by {{ homebrew_user }}

I suspect the Mactex cask or Munki cask ran an installer as root, which created this directory.

Maybe these directories should be added to the task "Ensure proper homebrew folders are in place.", so that they are created with the right permissions?

**Comment by elliotweiser** [comment]
Fixed in #125
