### ISSUE TITLE
Retries on install tasks?

### ISSUE THREAD

**Issue by deekayen** [geerlingguy/ansible-role-homebrew#128]
I'm occasionally getting failed tasks for homebrew and cask packages I know work. What do you think about a pull request that would add a retries argument to the homebrew and homebrew_cask tasks?

Some example failures:
https://travis-ci.org/deekayen/ansible-macbook/jobs/631728304
https://travis-ci.org/deekayen/ansible-macbook/jobs/632030388
https://travis-ci.org/deekayen/ansible-macbook/jobs/631556199

**Comment by geerlingguy** [comment]
I wouldn't necessarily be opposed to it if it's done simply. I haven't had this issue with the default set of packages I install on here or on my mac dev playbook elsewhere, though—maybe it's an issue with some of the packages you use in ansible-macbook?
