### ISSUE TITLE
ansible-galaxy install role --force vs ansible-galaxy update?

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-role-homebrew#136]
Inherited an older Mac and it had a very old version of ansible-role-homebrew installed and I blindly assumed  I could `ansible-galaxy update` but that threw an error. 

I found your ticket https://github.com/ansible/ansible/issues/6466 but that was closed(?) with a reference to https://github.com/ansible/proposals/issues/23

What is the proper way to upgrade this role? Use the `ansible-galaxy install ansible-role-homebrew --force`? The answer is probably for any role but this is the one I'm working on right now.

**Comment by ned300889** [comment]
Hey @basictheprogram,

Yes the current upgrade path is `ansible-galaxy install $ROLE --force`
