### ISSUE TITLE
`brew cask install` is deprecated in favour of `brew install --cask`

### ISSUE THREAD

**Issue by emilecantin** [geerlingguy/ansible-role-homebrew#155]
At the moment, I can't install any Casks using the role; I get errors like these:

```
failed: [127.0.0.1] (item=balenaetcher) => {"ansible_loop_var": "item", "changed": false, "item": "balenaetcher", "msg": "Error: Calling brew cask install is disabled! Use brew install [--cask] instead."}
```

[Looks like Homebrew themselves](https://brew.sh/2020/12/01/homebrew-2.6.0/) deprecated the `brew cask install` command in the latest version.

I'd submit a PR, but I'm relatively new to ansible and really can't understand how the install command is generated, so a bug report will have to do.

**Comment by tslmy** [comment]
Blocked by <https://github.com/ansible-collections/community.general/issues/1524>.

**Comment by geerlingguy** [comment]
Thanks; marking this appropriately so people see it more easily.

This will also affect Ansible 2.9 and earlier (for those locked into older versions).

**Comment by rmchale** [comment]
Is there a work around?

**Comment by qwerbzuio** [comment]
> Blocked by [ansible-collections/community.general#1524](https://github.com/ansible-collections/community.general/issues/1524).

Just a note that the blocking issue is now closed.

**Comment by tslmy** [comment]
You can install `community.general` from HEAD to get this working right now: `ansible-galaxy collection install --force git+https://github.com/ansible-collections/community.general.git`

Tested locally.

**Comment by geerlingguy** [comment]
This should be working now, as the latest Ansible releases include it :)
