### ISSUE TITLE
installing is very slow. 

### ISSUE THREAD

**Issue by dspolleke** [geerlingguy/ansible-role-homebrew#161]
On a virtual i created it takes ages to "ensure" packages. 
I suspect this is because for every item you perform multiple steps. 
What might be possible is to take the array of packages to install and grep that against the installed packages to get only the list of packages to install. 
It will require a Frankenstein command with subshells but I have gotten something similar working in another project. 
I can work out how to do it, and fork the project and submit a pull request but I cannot get my head around where the homebrew_cask: in tasks/main.yml comes from. Because you do not use a namespace i have no idea.

**Comment by geerlingguy** [comment]
I'd rather not write an entire parsing engine for Homebrew, but rather rely on Ansible's `homebrew` module, which should be well optimized already; if there are issues with performance, please consider debugging them and if there's a bug found with the way the module detects what's installed / what needs to be installed, please consider filing an upstream bug report: https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_module.html
