### ISSUE TITLE
execute local vs ssh

### ISSUE THREAD

**Issue by tuxpeople** [geerlingguy/ansible-role-homebrew#165]
Hi

When using my update playbook, which includes this role, over ssh it always fails at the install from Brewfile step: `mas installation failed`. I do have some `mas` lines in my [Brewfile](https://github.com/tuxpeople/dotfiles/blob/master/Brewfile).

However, when I run that on `localhost` it works.

What could I have done wrong?

**Comment by geerlingguy** [comment]
Closing all issues in this repository in preparation for a migration to `geerlingguy.mac`—see https://github.com/geerlingguy/ansible-role-homebrew/issues/166
