### ISSUE TITLE
Unable to use this role if /usr/local is not empty

### ISSUE THREAD

**Issue by ngpestelos** [geerlingguy/ansible-role-homebrew#18]
I encountered this problem when I was trying to run `mac-dev-playbook`. Before running the playbook, I installed ansible using pip. This role fails to clone the homebrew repo if /usr/local is not empty.

As a workaround, I installed homebrew manually, then re-ran the playbook.

**Comment by geerlingguy** [comment]
Is this still an issue (do you know)? I haven't had a chance to rebuild my OS X-inside-a-VM environment so it's difficult for me to quickly test.

**Comment by brettporter** [comment]
I'm not sure if it's related... it's currently failing on El Capitan for this reason, since it you need to jump in and run `sudo chown -R $(whoami):admin /usr/local` per the Homebrew instructions - is that the problem? I was planning to PR that soon.

**Comment by geerlingguy** [comment]
@brettporter - Yeah I've noticed that on some new builds... is there a simple/idempotent workaround for that?

**Comment by brettporter** [comment]
The `chown` above should suffice: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

**Comment by toby-griffiths** [comment]
That link is no longer working.  I'm having this problem on a freshly build Yosemite build this evening.

**Comment by geerlingguy** [comment]
@toby-griffiths - Did you try `sudo chown -R $(whoami):admin /usr/local` ?

**Comment by toby-griffiths** [comment]
@geerlingguy I didn't.  I thought that it wouldn't do the git install, even if the permissions were correct?

**Comment by supertylerc** [comment]
This issue still exists.  Although #22 solved permissions issues, this is still a problem because Ansible doesn't have a way to do a `git init` followed by adding remotes and fetching.  The only way to fix this right now is to use the script provided by Homebrew.  This could be done using the `shell` module and adding a `creates` parameter that points at the `brew` executable.

**Comment by geerlingguy** [comment]
That seems like it would be an acceptable solution. I don't have time to work on it, but if someone wants to send over a PR I can test it and merge if it works fine.

**Comment by andrewkboyd** [comment]
I got this working by cloning homebrew into `/tmp/brew`, then using `synchronize` to merge the directories when brew isn't already in local.  I will try to get to making it a PR this weekend.

**Comment by scottrigby** [comment]
@geerlingguy @supertylerc Yep, I ran into this issue when installing packages globally via Composer – I need to run `sudo chown -R $(whoami):admin /usr/local` each time or else the process halts at:
```bash
TASK [geerlingguy.homebrew : Setup homebrew install path.] *********************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "timeout waiting for privilege escalation password prompt:\n\nWe trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:\n\n    #1) Respect the privacy of others.\n    #2) Think before you type.\n    #3) With great power comes great responsibility.\n\n[sudo via ansible, key=guzukybroakedlvsbuahrnwmywdyxpea] password: "}
```
I haven't tried the solution by @andrewkboyd just above, so I can't speak to that. But I just made a PR with the script from Homebrew above: https://github.com/geerlingguy/ansible-role-homebrew/pull/26

**Comment by ksylvan** [comment]
Seems like the role's intent (to install home-brew if it's not already there) isn't working. I just tried this on a fresh El Capitan install and tried this and ran into the same issue even with the chown. Doing a home-brew install via the `ruby -e ...` method that is recommended on the homepage gets around this. So perhaps doing that (instead of the `git clone`) in an unattended manner is the right way to go?

**Comment by geerlingguy** [comment]
I'd like to go with the approach in https://github.com/geerlingguy/ansible-role-homebrew/pull/30 — just haven't had time to review and merge yet (hopefully I'll be getting some time soon!).

**Comment by ksylvan** [comment]
You'll have to also take into account that the (now legacy) homebrew repo is now split into two repositories. See the README here: https://github.com/Homebrew/legacy-homebrew

**Comment by ksylvan** [comment]
Hitting this on Sierra now:

    TASK [geerlingguy.homebrew : Ensure homebrew is installed.] ********************
    fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/git clone
      --origin origin --branch master --depth 1 git://github.com/Homebrew/homebrew.git /usr/local",
     "failed": true, "msg": "fatal: destination path '/usr/local' already exists and is not an empty
     directory.", "rc": 128, "stderr": "fatal: destination path '/usr/local' already exists and is
    not an empty directory.\n", "stdout": "", "stdout_lines": []}

**Comment by geerlingguy** [comment]
Closing in favor of #35.
