### ISSUE TITLE
cask programs only work if previously installed?

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-homebrew#29]
cask items are only processed if `brew cask list` contains the entry.

It would be convenient for me (and others I imagine) if there was an easy boolean switch to always run, or have an array of items which install if they haven't previously been installed.

What are your recommendations for this?

**Comment by fubarhouse** [comment]
I'm going to do some testing, reading the code doesn't make total sense for what's happening.
I'll report back and close if required.

**Comment by geerlingguy** [comment]
:) When I glanced at the original issue report I was wondering how that would be possible, since it seems to be working for me with new items added to the list... good to know it's working okay!
