### ISSUE TITLE
Refactor role for Homebrew 1.0.0+ compatibility

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-homebrew#35]
It seems [Homebrew 1.0.0](http://brew.sh/2016/09/21/homebrew-1.0.0/) has introduced a few changes that cause things to break a little with this role.

I will still not recommend—or personally use, on principle—the curl-install-script-to-install method, except as a last resort, so the role will need some refactoring.

## Things to fix

  - [ ] Homebrew installation not working due to repo split (see #32)
  - [ ] Pathing based on new install location in `/usr/local/Homebrew` (instead of `/usr/local` — see #18)
  - [ ] Other emergent issues

**Comment by ksylvan** [comment]
+1 Thank you.

**Comment by geerlingguy** [comment]
I got this all working, it's now at tag 2.0.0.

I've updated the entire installation process to do the exact same steps as the incredibly convoluted install file (https://raw.githubusercontent.com/Homebrew/install/master/install).

Assumes (like before) that you already have `ansible` and `git` locally.

**Comment by ksylvan** [comment]
Thank you! Works great.

**Comment by geerlingguy** [comment]
@ksylvan - Motivation was because I finally upgraded to Sierra, so had to do it or risk not having everything in my life automated!!

**Comment by ksylvan** [comment]
Ha ha. Yes, I totally get that. Have an awesome day.
