### ISSUE TITLE
Is aggregation of variables (e.g. homebrew_installed_packages) possible?

### ISSUE THREAD

**Issue by bilke** [geerlingguy/ansible-role-homebrew#43]
Is it possible to aggregate e.g. `homebrew_installed_packages` from different sources? In my case I would like to have some Homebrew packages to install defined in

1. A Role (`roles/myrole/vars/main.yml`)
2. Another role (`roles/anotherrole/vars/main.yml`)
3. Host specific (`host_vars/myhost.yml`)
4. Group specific (`group_vars/mygroup/vars.yml`)

Unfortunately only packages defined in my first role are installed. Is this kind of aggregation possible? Thanks!

**Comment by geerlingguy** [comment]
At this time, with the way the role is structured, no; but you can define a task (maybe in `pre_tasks`) to combine multiple differently-named variables (e.g. `{{ list1 + list2 }}`).

See this answer: [How to concatenate lists in Ansible/Jinja2](http://stackoverflow.com/a/31045409)

For this particular role, I'm going to leave the task as-is so it will only use one list, but that list could be set via `set_fact` using a task that uses the above concatenation/combination approach.
