### ISSUE TITLE
Pre-downloading role

### ISSUE THREAD

**Issue by trusk89** [geerlingguy/ansible-role-homebrew#71]
Hey,

 Basically I have 3 scripts that run some ansible tasks which depend on your two roles. So as I don't have to repeatedly download them as requirements on multiple machines, I would like to bundle the roles on my internal(company) git repo, together with my scripts.

Do you know of any way that I might achieve that?

Thanks

**Comment by elliotweiser** [comment]
Tell Ansible via the `ansible.cfg` file where to look for installed roles:
http://docs.ansible.com/ansible/intro_configuration.html#roles-path

Install your requirements to that directory:

```bash
ansible-galaxy install -r requirements.yml -p /path/to/git/repo/roles
```

Then commit the roles directory to your repository.

That said, I'm curious why you'd need to install the roles on multiple machines. You should only need to download the roles once onto the control node. It may not be feasible in your company, but with one control node, you should be able to manage multiple other machines if they are enumerated in the control node's inventory. 

http://docs.ansible.com/ansible/intro_inventory.html

**Comment by geerlingguy** [comment]
@trusk89 - Indeed, as @elliotweiser says, for stability and performance it's often desirable to 'commit your dependencies'; see how Drupal VM does it here: https://github.com/geerlingguy/drupal-vm/tree/master/provisioning

For most of my 'actual money-earning production' playbooks, I add an `ansible.cfg` with the roles_path defined, then commit the roles to the repo.

**Comment by trusk89** [comment]
Yeah, I did that and it works pretty well. One thing i don't get yet (didn't have time to test before leaving work): if I have my roles already stored on my repo, do I need to run ansible-galaxy install requirements.yml? Or they are automatically searched for and found in the path I set in ansible.cfg?

Thanks for all the help guys!

**Comment by elliotweiser** [comment]
The `ansible-galaxy` command will search the paths enumerated in the `roles_path` variable defined in your `ansible.cfg`. Therefore, as long as the roles are committed somewhere in that list of paths, `ansible-galaxy` will not need to re-download them unless you force `-f` it.

**Comment by trusk89** [comment]
@elliotweiser so I can remove the step from my scripts, right?

**Comment by elliotweiser** [comment]
Go for it.

**Comment by trusk89** [comment]
Thanks again guys!

**Comment by geerlingguy** [comment]
No problem! Also, note that `ansible-galaxy` isn't a full fledged package manager (at least not yet), so when updating things, you might have to delete a package then install, or use `--force` to force install a newer version.

**Comment by trusk89** [comment]
It isn't, but what it is, is great! I managed to automate env setup for 3 machines: a jenkins master, a jenkins build slave and an iOS/Android development machine. It's great!

**Comment by trusk89** [comment]
Works great, thanks!
