### ISSUE TITLE
Permission issue with directory '/usr/local/var/homebrew/'

### ISSUE THREAD

**Issue by makkus** [geerlingguy/ansible-role-homebrew#76]
Never had this problem before, not quite sure where the issue is.

Tried to apply this role onto a clean 'El Capitan' vagrant box, and getting this error message:

TASK [geerlingguy.homebrew : Force update brew after installation.] ************
task path: /Users/vagrant/.freckles/runs/archive/run_170801_23_36_48/roles/internal/geerlingguy.homebrew/tasks/main.yml:61
Using module file /Users/vagrant/.local/opt/conda/envs/inaugurate/lib/python2.7/site-packages/ansible/modules/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/usr/local/bin/brew", 
        "update", 
        "--force"
    ], 
    "delta": "0:00:00.646622", 
    "end": "2017-08-01 23:41:23.749635", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/local/bin/brew update --force", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 1, 
    "start": "2017-08-01 23:41:23.103013", 
    "stderr": "mkdir: /usr/local/var/homebrew/locks: Permission denied\nError: Can't create update lock in /usr/local/var/homebrew/locks!\nFix permissions by running:\n  sudo chown -R $(whoami) /usr/local/var/homebrew", 
    "stderr_lines": [
        "mkdir: /usr/local/var/homebrew/locks: Permission denied", 
        "Error: Can't create update lock in /usr/local/var/homebrew/locks!", 
        "Fix permissions by running:", 
        "  sudo chown -R $(whoami) /usr/local/var/homebrew"
    ], 
    "stdout": "", 
    "stdout_lines": []
}

It looks like homebrew expects a directory '/usr/local/var/homebrew', and write access to it. It should be easy enough to add a task to create that, but I'm not sure whether I'm not maybe missing something else?

**Comment by makkus** [comment]
Right. Some more testing and it looks like 'Sierra' is affected as well. Getting the same error message. Will probably need to add a check for Mac OS version. Might send a pull request if I get to it today.

**Comment by geerlingguy** [comment]
Merged, thanks for the PR!
