### ISSUE TITLE
Check for Command Line Tools in Software Update list hangs

### ISSUE THREAD

**Issue by SurferL** [geerlingguy/ansible-role-homebrew#86]
It seems that the step `Check for Command Line Tools in Software Update list` occasionally hangs and therefore breaks the build. 

Could be something to do with this? https://apple.stackexchange.com/questions/82551/mac-app-store-update-stuck-installing-calculating

Is there anyway I can work around this, perhaps by adding a retry after x time?

**Comment by elliotweiser** [comment]
@SurferL That looks more like a possible issue with the dependency role https://github.com/elliotweiser/ansible-osx-command-line-tools. Please open an issue on that role so we can discuss it there and I'll link it back to this one.
