### ISSUE TITLE
Cask task fails 

### ISSUE THREAD

**Issue by anthonygreen** [geerlingguy/ansible-role-homebrew#9]
TASK: [geerlingguy.homebrew | Get list of apps installed with cask.] ********** 
    failed: [io] => {"changed": false, "cmd": "brew cask list", "failed": true, "rc": 2}
    msg: [Errno 2] No such file or directory

**Comment by geerlingguy** [comment]
It seems this may be a problem with cask / the OS environment rather than this role (it's working for me on 10.10.3 and also on a fresh/clean VM running 10.10.2)... is there anything helpful in this upstream issue? https://github.com/caskroom/homebrew-cask/issues/4667

**Comment by geerlingguy** [comment]
Also, did you override the `homebrew_taps` variable in your own playbook?

It should at least have:

```yaml
homebrew_taps:
  - caskroom/cask
```

**Comment by anthonygreen** [comment]
The playbook is
---
- hosts: io
  roles:
    - { role: geerlingguy.homebrew }

**Comment by anthonygreen** [comment]
Getting the same error following an upgrade to 10.10.3

**Comment by anthonygreen** [comment]
I'm encountering the same issue with a Vagrant OSX image

<localhost> ESTABLISH CONNECTION FOR USER: vagrant
<localhost> REMOTE_MODULE command brew cask list
<localhost> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/greena28/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 localhost /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434016348.08-262225023919227 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434016348.08-262225023919227 && echo $HOME/.ansible/tmp/ansible-tmp-1434016348.08-262225023919227'
<localhost> PUT /var/folders/sm/vgbwtrps3yv2yl79n43t_f916ldxgl/T/tmpZeM1uc TO /Users/vagrant/.ansible/tmp/ansible-tmp-1434016348.08-262225023919227/command
<localhost> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/greena28/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 localhost /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/vagrant/.ansible/tmp/ansible-tmp-1434016348.08-262225023919227/command; rm -rf /Users/vagrant/.ansible/tmp/ansible-tmp-1434016348.08-262225023919227/ >/dev/null 2>&1'
failed: [test] => {"changed": false, "cmd": "brew cask list", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

**Comment by anthonygreen** [comment]
NB The ansible module for homebrew does work

- homebrew: name=brew-cask state=present

**Comment by fhickman** [comment]
I had this same problem. It looks like it is due to the 'command' module not finding 'brew' on whatever path it is using. If you change the command to '/usr/local/bin/brew cask list', it should work.

**Comment by geerlingguy** [comment]
Added new variable in commit above, so this role should be a bit more robust in situations where the $PATH doesn't include `/usr/local/bin`.
