### ISSUE TITLE
Builds failing with 'error: failed to tap: caskroom/cask'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-homebrew#93]
Example: https://travis-ci.org/geerlingguy/ansible-role-homebrew/jobs/384750906#L5354

```
TASK [ansible-role-homebrew : Ensure configured taps are tapped.] **************
ok: [localhost] => (item=homebrew/core)
failed: [localhost] (item=caskroom/cask) => {"changed": false, "item": "caskroom/cask", "msg": "added: 0, unchanged: 0, error: failed to tap: caskroom/cask"}
```

Looks like it may now be `homebrew/cask` instead of `caskroom/cask`.

**Comment by geerlingguy** [comment]
This is also breaking my `geerlingguy.mas` role, and my `mac-dev-playbook` Ansible project... Grr.

**Comment by geerlingguy** [comment]
Fixed via above commit!

**Comment by commjoen** [comment]
Hi there, I know the issue is closed, but it seems i get the same behavior, using Mac OS X 10.13.6, geerlingguy.homebrew 2.5.0, Ansible 2.6.2 and brew version 1.7.1 . How can I fix this?

**Comment by commjoen** [comment]
Fixed it: I was running it with become, should have removed that ;-)
