### ISSUE TITLE
Role runs incorrectly as root when running on remote system

### ISSUE THREAD

**Issue by shadowink** [geerlingguy/ansible-role-homebrew#94]
I'm trying to use this role for setting up our mac build nodes.  When it runs remotely via ssh, the commands start to run as root, and Homebrew is installed in a broken state. 

The command I run is:
**ansible-playbook -i "192.168.56.102," -b -u build -k -K mac-node-setup.yml **

ansible-playbook is v 2.5.3, installed on the local machine by Homebrew

On a fresh installed High Sierra VM, the role is throwing an error at

> TASK [homebrew : Ensure configured taps are tapped.] *****************************************************************************************
> task path: /Users/alberghi/repos/buildtest/roles/homebrew/tasks/main.yml:99
> failed: [192.168.56.102] (item=homebrew/core) => {"changed": false, "item": "homebrew/core", "msg": "added: 0, unchanged: 0, error: failed to tap: homebrew/core"}
> failed: [192.168.56.102] (item=homebrew/cask) => {"changed": false, "item": "homebrew/cask", "msg": "added: 0, unchanged: 0, error: failed to tap: homebrew/cask"} 

Running **brew tap** directly on the machine throws a permissions error: 

> build$ brew tap
> Error: /usr/local/Cellar is not writable. You should change the
> ownership and permissions of /usr/local/Cellar back to your
> user account:
>   sudo chown -R $(whoami) /usr/local/Cellar

Dumping the facts on the VM shows: ansible_user_id": "root" which means that Homebrew is installed owned by root.  Many of the tasks in the second half are running as root, and those fail as brew commands because of security settings in homebrew.

To get it running on my systems I had to make two changes.

First, I had to explicity set ansible_user_id to ansible_env.SUDO_USER in vars:
`    ansible_user_id: "{{ ansible_env.SUDO_USER }}" `

Second, I split the roles main.yml into two blocks.  The first one, which installs and sets permissions, runs as root.  The second, which runs brew installs, runs as ansible_user_id.  This seems to have fixed the problems.

**Comment by elliotweiser** [comment]
Are you trying to install Homebrew as `root`? Because that's what seems to be happening. You're using `-b` (synonymous w/ `--become`), which invokes privilege escalation. To my knowledge, installing as `root` is not recommended, but that might not be what you had in mind.

**Comment by mindrunner** [comment]
Same/Similar problem here.

Worked before without any problems.


```
17:34:40 TASK [danbohea.homebrew : Add caskroom/cask tap.] ******************************
17:34:40 task path: /var/jenkins_home/jobs/osx-maintenance/jobs/osx.ios.update-macmini-as-builnode/workspace/ansible/roles/danbohea.homebrew/tasks/main.yml:15
17:34:40 Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/packaging/os/homebrew_tap.py
17:34:40 <wzumacmini6> ESTABLISH SSH CONNECTION FOR USER: ****
17:34:40 <wzumacmini6> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=**** -o ConnectTimeout=10 -o ControlPath=/var/jenkins_home/.ansible/cp/7d0d10de5e wzumacmini6 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
17:34:41 <wzumacmini6> (0, '/Users/****\n', '')
17:34:41 <wzumacmini6> ESTABLISH SSH CONNECTION FOR USER: ****
17:34:41 <wzumacmini6> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=**** -o ConnectTimeout=10 -o ControlPath=/var/jenkins_home/.ansible/cp/7d0d10de5e wzumacmini6 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897 `" && echo ansible-tmp-1528126480.96-253562112348897="` echo /Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897 `" ) && sleep 0'"'"''
17:34:41 <wzumacmini6> (0, 'ansible-tmp-1528126480.96-253562112348897=/Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897\n', '')
17:34:41 <wzumacmini6> PUT /tmp/tmpDC2igb TO /Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897/homebrew_tap.py
17:34:41 <wzumacmini6> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=**** -o ConnectTimeout=10 -o ControlPath=/var/jenkins_home/.ansible/cp/7d0d10de5e '[wzumacmini6]'
17:34:41 <wzumacmini6> (0, 'sftp> put /tmp/tmpDC2igb /Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897/homebrew_tap.py\n', '')
17:34:41 <wzumacmini6> ESTABLISH SSH CONNECTION FOR USER: ****
17:34:41 <wzumacmini6> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=**** -o ConnectTimeout=10 -o ControlPath=/var/jenkins_home/.ansible/cp/7d0d10de5e wzumacmini6 '/bin/sh -c '"'"'chmod u+x /Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897/ /Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897/homebrew_tap.py && sleep 0'"'"''
17:34:41 <wzumacmini6> (0, '', '')
17:34:41 <wzumacmini6> ESTABLISH SSH CONNECTION FOR USER: ****
17:34:41 <wzumacmini6> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=**** -o ConnectTimeout=10 -o ControlPath=/var/jenkins_home/.ansible/cp/7d0d10de5e -tt wzumacmini6 '/bin/sh -c '"'"'/usr/local/bin/python2 /Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897/homebrew_tap.py; rm -rf "/Users/****/.ansible/tmp/ansible-tmp-1528126480.96-253562112348897/" > /dev/null 2>&1 && sleep 0'"'"''

17:34:49 <wzumacmini6> (0, '\r\n{"msg": "added: 0, unchanged: 0, error: failed to tap: caskroom/cask", "failed": true, "invocation": {"module_args": {"url": null, "state": "present", "tap": "caskroom/cask", "name": ["caskroom/cask"]}}}\r\n', 'Shared connection to wzumacmini6 closed.\r\n')
17:34:49 fatal: [wzumacmini6]: FAILED! => {
17:34:49     "changed": false, 
17:34:49     "invocation": {
17:34:49         "module_args": {
17:34:49             "name": [
17:34:49                 "caskroom/cask"
17:34:49             ], 
17:34:49             "state": "present", 
17:34:49             "tap": "caskroom/cask", 
17:34:49             "url": null
17:34:49         }
17:34:49     }
17:34:49 }
17:34:49 
17:34:49 MSG:
17:34:49 
17:34:49 added: 0, unchanged: 0, error: failed to tap: caskroom/cask
17:34:49 
17:34:49 	to retry, use: --limit @/var/jenkins_home/jobs/osx-maintenance/jobs/osx.ios.update-macmini-as-builnode/workspace/ansible/playbook.retry
```

**Comment by geerlingguy** [comment]
@GabLeRoux for the caskroom issue, please see: https://github.com/geerlingguy/ansible-role-homebrew/issues/93 — this was fixed in the defaults, needs to be `homebrew/cask` now.

**Comment by elliotweiser** [comment]
Closing since there's been no follow-up, and I'm convinced that setting `-b` on the command line is the source of the problem that was originally reported.
