### ISSUE TITLE
Failing with 'error: failed to tap: homebrew/core'

### ISSUE THREAD

**Issue by I-Dont-Remember** [geerlingguy/ansible-role-homebrew#95]
I'm trying to create something similar to your mac-dev-playbook and am seeing this issue:
```
failed: [127.0.0.1] (item=homebrew/core) => {"changed": false, "item": "homebrew/core", "msg": "added: 0, unchanged: 0, error: failed to tap: homebrew/core"}
failed: [127.0.0.1] (item=homebrew/cask) => {"changed": false, "item": "homebrew/cask", "msg": "added: 0, unchanged: 0, error: failed to tap: homebrew/cask"}
```
I tried installing them before running the playbook to see if it made any difference, but no luck.
Testing inside this Vagrant High Sierra box https://app.vagrantup.com/jhcook/boxes/macos-sierra.
Looks like it might be an issue with [homebrew_tap](http://docs.ansible.com/ansible/latest/modules/homebrew_tap_module.html).

**Comment by I-Dont-Remember** [comment]
Oddly, it now works with expected behaviour.  Closing for now since there's nothing to go off of.

**Comment by commjoen** [comment]
Hi there, I know the issue is closed, but it seems i get the same behavior, using Mac OS X 10.13.6, geerlingguy.homebrew 2.5.0, Ansible 2.6.2 and brew version 1.7.1 . What am I doing wrong?
